### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by knutanton** [dmlib/nobody_puts_swayze_in_a_coffin#3]
do we need a licence explaining how our stuff can be used?

**Comment by dmlib** [comment]
Good idea :+1:

**Comment by dmlib** [comment]
Do you think it is a great idea @lsfrsr og @mabu-lib ?

**Comment by lsfrsr** [comment]
Yes, good idea.

**Comment by mabu-lib** [comment]
Good idea!
